[package]
name = "yew-tailwind"
version = "0.1.0"
edition = "2021"

[dependencies]
js-sys = "0.3.77"
web-sys = "0.3.77"
yew = { git = "https://github.com/yewstack/yew/", features = ["csr"] }
tokio = "1.46.1"
wasm-bindgen = "0.2.100"
